name: Personal-Details
on: push
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
          - name: my-first-name
            run: echo "Abhilash"
            
          - name: my-last-name
            run: echo "Mishra"
            
          - name: my-age
            run: echo 31
            
          - name: Profession
            run: echo "DevOps Engineer"
            
